<?php

namespace Livewirez\Billing\Lib;

use Livewirez\Billing\Traits\ArchTechTrait; 
use Livewirez\Billing\Interfaces\CurrencyType;
use Livewirez\Billing\Traits\CurrencyTypeTrait;

/**
 * @see https://www.iban.com/currency-codes
 * @see https://en.wikipedia.org/wiki/ISO_4217
 * @see https://www.iso.org/iso-4217-currency-codes.html
 */
enum FiatCurrencyCode: string implements CurrencyType
{
    use ArchTechTrait, CurrencyTypeTrait; 

    case AFN = "AFN";
    case ALL = "ALL";
    case DZD = "DZD";
    case USD = "USD";
    case EUR = "EUR";
    case AOA = "AOA";
    case XCD = "XCD";
    case ARS = "ARS";
    case AMD = "AMD";
    case AWG = "AWG";
    case AUD = "AUD";
    case AZN = "AZN";
    case BSD = "BSD";
    case BHD = "BHD";
    case BDT = "BDT";
    case BBD = "BBD";
    case BYN = "BYN";
    case BZD = "BZD";
    case XOF = "XOF";
    case BMD = "BMD";
    case BTN = "BTN";
    case INR = "INR";
    case BOB = "BOB";
    case BOV = "BOV";
    case BAM = "BAM";
    case BWP = "BWP";
    case NOK = "NOK";
    case BRL = "BRL";
    case BND = "BND";
    case BGN = "BGN";
    case BIF = "BIF";
    case CVE = "CVE";
    case KHR = "KHR";
    case XAF = "XAF";
    case KYD = "KYD";
    case CLF = "CLF";
    case CLP = "CLP";
    case CNY = "CNY";
    case COP = "COP";
    case COU = "COU";
    case KMF = "KMF";
    case CDF = "CDF";
    case NZD = "NZD";
    case CRC = "CRC";
    case CUC = "CUC";
    case CUP = "CUP";
    case XCG = "XCG";
    case CZK = "CZK";
    case DKK = "DKK";
    case DJF = "DJF";
    case DOP = "DOP";
    case EGP = "EGP";
    case SVC = "SVC";
    case ERN = "ERN";
    case ETB = "ETB";
    case FKP = "FKP";
    case FJD = "FJD";
    case XPF = "XPF";
    case GMD = "GMD";
    case GEL = "GEL";
    case GHS = "GHS";
    case GIP = "GIP";
    case GTQ = "GTQ";
    case GBP = "GBP";
    case GNF = "GNF";
    case GYD = "GYD";
    case HTG = "HTG";
    case HNL = "HNL";
    case HKD = "HKD";
    case HUF = "HUF";
    case ISK = "ISK";
    case IDR = "IDR";
    case XDR = "XDR";
    case IRR = "IRR";
    case IQD = "IQD";
    case ILS = "ILS";
    case JMD = "JMD";
    case JOD = "JOD";
    case KZT = "KZT";
    case KES = "KES";
    case KPW = "KPW";
    case KRW = "KRW";
    case KWD = "KWD";
    case KGS = "KGS";
    case LAK = "LAK";
    case LBP = "LBP";
    case LSL = "LSL";
    case ZAR = "ZAR";
    case LRD = "LRD";
    case LYD = "LYD";
    case CHF = "CHF";
    case MOP = "MOP";
    case MGA = "MGA";
    case MWK = "MWK";
    case MYR = "MYR";
    case MVR = "MVR";
    case MRU = "MRU";
    case MUR = "MUR";
    case XUA = "XUA";
    case MXN = "MXN";
    case MXV = "MXV";
    case MDL = "MDL";
    case MNT = "MNT";
    case MAD = "MAD";
    case MZN = "MZN";
    case MMK = "MMK";
    case NAD = "NAD";
    case NPR = "NPR";
    case NIO = "NIO";
    case NGN = "NGN";
    case OMR = "OMR";
    case PKR = "PKR";
    case PAB = "PAB";
    case PGK = "PGK";
    case PYG = "PYG";
    case PEN = "PEN";
    case PHP = "PHP";
    case PLN = "PLN";
    case QAR = "QAR";
    case MKD = "MKD";
    case RON = "RON";
    case RUB = "RUB";
    case RWF = "RWF";
    case SHP = "SHP";
    case WST = "WST";
    case STN = "STN";
    case SAR = "SAR";
    case RSD = "RSD";
    case SCR = "SCR";
    case SLE = "SLE";
    case SGD = "SGD";
    case XSU = "XSU";
    case SBD = "SBD";
    case SOS = "SOS";
    case SSP = "SSP";
    case LKR = "LKR";
    case SDG = "SDG";
    case SRD = "SRD";
    case SZL = "SZL";
    case SEK = "SEK";
    case CHE = "CHE";
    case CHW = "CHW";
    case SYP = "SYP";
    case TWD = "TWD";
    case TJS = "TJS";
    case TZS = "TZS";
    case THB = "THB";
    case TOP = "TOP";
    case TTD = "TTD";
    case TND = "TND";
    case TRY = "TRY";
    case TMT = "TMT";
    case UGX = "UGX";
    case UAH = "UAH";
    case AED = "AED";
    case USN = "USN";
    case UYI = "UYI";
    case UYU = "UYU";
    case UZS = "UZS";
    case VUV = "VUV";
    case VEF = "VEF";
    case VED = "VED";
    case VND = "VND";
    case YER = "YER";
    case ZMW = "ZMW";
    case ZWL = "ZWL";
}