<?php

namespace Livewirez\Billing\Lib\PayPal\Enums;

enum VaultUsagePattern: string
{
    case IMMEDIATE = 'IMMEDIATE';
    case DEFERRED = 'DEFERRED';
    case RECURRING_PREPAID = 'RECURRING_PREPAID';
    case RECURRING_POSTPAID = 'RECURRING_POSTPAID';
    case THRESHOLD_PREPAID = 'THRESHOLD_PREPAID';
    case THRESHOLD_POSTPAID = 'THRESHOLD_POSTPAID';
    case UNSCHEDULED_PREPAID = 'UNSCHEDULED_PREPAID';
    case UNSCHEDULED_POSTPAID = 'UNSCHEDULED_POSTPAID';
    case SUBSCRIPTION_PREPAID = 'SUBSCRIPTION_PREPAID';
    case SUBSCRIPTION_POSTPAID = 'SUBSCRIPTION_POSTPAID';
    case INSTALLMENT_PREPAID = 'INSTALLMENT_PREPAID';
    case INSTALLMENT_POSTPAID = 'INSTALLMENT_POSTPAID';
}